apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: datapvc
  name: datapvc
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
