version: "3"
services: 
  mymongo:
    image: mongo 
    volumes:
      - "data:/data/db"
  web:
    build: 
      context: .
      dockerfile: DockerfileCI
    ports: 
      - "8080:8090"
    depends_on: 
      - mymongo  
    links:
      - mymongo:mymongodb
volumes:
  data:
