apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mymongo
  name: mymongodb
spec:
  replicas: 2
  selector:
      matchLabels:
        app: mymongo  
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
      - image: mongo:4.4.2-bionic
        name: mymongo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        # resources: {}
        # volumeMounts:
        # - mountPath: /data/db
        #   name: datapvc
      restartPolicy: Always
      # volumes:
      # - name: datapvc
      #   persistentVolumeClaim:
      #     claimName: datapvc
# status: {}
